import { useState } from "react";

// ─── 数据库 ───────────────────────────────────────────────────────────────────
const DB = [
  {
    id: 1, name: "北京大学", short: "北大", city: "北京", province: "北京", level: "985/211",
    employment: 96, postgraduate: 92, city_score: 99, dormitory: 72, canteen: 80, environment: 95, transferDifficulty: "较难",
    pros: ["校友网络覆盖政商学各界", "图书馆资源全国最强", "国际交流机会多", "品牌溢价极高"],
    cons: ["竞争压力极大", "部分宿舍老旧", "北京生活成本高", "内卷氛围明显"],
    suitable: ["目标政府/学术/顶级机构", "能承受高压竞争", "有清晰长期规划"],
    unsuitable: ["希望轻松大学生活", "对排名不在意只想学技术", "经济压力较大的家庭"],
    dormDesc: "4-6人间为主，部分老宿舍楼无独立卫浴，近年新楼条件改善。月均住宿约100元。",
    canteenDesc: "食堂数量多、口味多样，价格亲民，总体评价较好。",
    majors: ["法学", "中文", "数学", "物理", "经济学", "国际关系", "哲学"],
    reviews: [
      { type: "学霸", text: "资源天花板，只要你能卷进去，机会真的是别处给不了的。但心理压力也是真实的，要做好准备。", trustScore: 91 },
      { type: "普通学生", text: "图书馆是我四年最爱的地方。宿舍确实一般，但你很快就不在乎了，因为外面的世界太精彩。", trustScore: 88 },
      { type: "压线学生", text: "压线进来第一学期很难熬，但熬过去之后发现平台给的机会值得。别被绩点焦虑打倒。", trustScore: 85 },
    ],
    scoreLines: { "北京": 682, "广东": 676, "湖南": 671, "河南": 679 },
    riskLevel: "极高",
  },
  {
    id: 2, name: "清华大学", short: "清华", city: "北京", province: "北京", level: "985/211",
    employment: 98, postgraduate: 95, city_score: 99, dormitory: 80, canteen: 85, environment: 96, transferDifficulty: "难",
    pros: ["工科实验室设施顶级", "大厂直通车，薪资天花板", "创业资源丰富", "校企合作极强"],
    cons: ["学业压力全国最大", "文科资源相对弱", "竞争极度激烈", "ddl永远赶不完"],
    suitable: ["目标大厂/创业/顶级工程师", "理工科天赋强", "能承受极高强度学习"],
    unsuitable: ["文科生", "希望有大量自由时间", "不喜欢竞争环境"],
    dormDesc: "6人间为主，近年新建宿舍楼有空调，条件较好。部分楼层老旧。",
    canteenDesc: "食堂众多，品质稳定，价格合理，深受学生好评。",
    majors: ["计算机", "电子工程", "机械", "建筑", "经管", "材料", "自动化"],
    reviews: [
      { type: "学霸", text: "cs专业毕业直接sp/ssp，实验室设备真的好，部分课程直接用工业级设备。值得所有付出。", trustScore: 94 },
      { type: "普通学生", text: "压力是真的大，但毕业那一刻拿到offer你会觉得值。宿舍6人间还行，比想象中好。", trustScore: 87 },
      { type: "压线学生", text: "压线进来非常煎熬，建议提前做好心理建设。不过平台真的好，坚持下来不会后悔。", trustScore: 82 },
    ],
    scoreLines: { "北京": 688, "广东": 681, "湖南": 678, "河南": 685 },
    riskLevel: "极高",
  },
  {
    id: 3, name: "浙江大学", short: "浙大", city: "杭州", province: "浙江", level: "985/211",
    employment: 93, postgraduate: 88, city_score: 91, dormitory: 90, canteen: 88, environment: 92, transferDifficulty: "中等",
    pros: ["紫金港新校区宿舍4人间有独卫", "阿里系校友资源极强", "杭州互联网实习机会多", "创业生态成熟"],
    cons: ["校区分散", "竞争激烈", "文科资源相对少", "杭州消费水平较高"],
    suitable: ["目标互联网/创业", "喜欢杭州城市氛围", "理工科为主"],
    unsuitable: ["不喜欢互联网方向", "希望校区集中", "文科生首选"],
    dormDesc: "紫金港新校区4人间独立卫浴，条件优秀。老校区条件一般。",
    canteenDesc: "食堂品种丰富，口味偏江浙，价格适中，总体评价好。",
    majors: ["计算机", "农学", "医学", "材料", "电子", "机械", "软件工程"],
    reviews: [
      { type: "学霸", text: "阿里内推真的方便，校友圈子大。宿舍是我见过985里最好的，4人间有独卫。", trustScore: 92 },
      { type: "普通学生", text: "杭州真的适合年轻人，实习机会比北京都不差。食堂很好吃，性价比高。", trustScore: 89 },
      { type: "压线学生", text: "压线进来第一年GPA竞争很激烈，但宿舍条件好让我心情好了不少。慢慢就适应了。", trustScore: 84 },
    ],
    scoreLines: { "浙江": 675, "广东": 668, "湖南": 663, "河南": 671 },
    riskLevel: "高",
  },
  {
    id: 4, name: "武汉大学", short: "武大", city: "武汉", province: "湖北", level: "985/211",
    employment: 84, postgraduate: 86, city_score: 78, dormitory: 75, canteen: 82, environment: 99, transferDifficulty: "中等",
    pros: ["全国最美校园公认第一", "遥感测绘全国第一", "武汉生活成本低", "校园文化氛围好"],
    cons: ["地处中部就业资源不如沿海", "宿舍在山上爬坡费体力", "武汉夏热冬冷", "部分专业就业竞争力一般"],
    suitable: ["喜欢人文校园氛围", "目标科研/学术", "预算有限的家庭"],
    unsuitable: ["目标金融/互联网沿海大厂", "怕爬坡怕冷热", "就业优先考虑"],
    dormDesc: "4-6人间，依山而建，部分宿舍视野极好但需爬坡，老楼设施一般。",
    canteenDesc: "食堂品种多，武汉口味为主，价格实惠，总体评价不错。",
    majors: ["遥感测绘", "法学", "信息管理", "水利", "外语", "哲学", "历史"],
    reviews: [
      { type: "学霸", text: "校园美到哭，每年樱花季游客比学生多。测绘遥感全国第一不是吹的，就业去向很好。", trustScore: 90 },
      { type: "普通学生", text: "爬坡是真的累，但住在山上看日出是真的美。武汉消费低，生活压力小很多。", trustScore: 88 },
      { type: "压线学生", text: "压线进来选专业选到了法学，感觉还不错。校园环境真的是心理疗愈，减压效果满分。", trustScore: 83 },
    ],
    scoreLines: { "湖北": 645, "广东": 638, "湖南": 633, "河南": 641 },
    riskLevel: "中",
  },
  {
    id: 5, name: "南京大学", short: "南大", city: "南京", province: "江苏", level: "985/211",
    employment: 87, postgraduate: 91, city_score: 82, dormitory: 76, canteen: 79, environment: 86, transferDifficulty: "较难",
    pros: ["学术风气全国顶尖", "天文地质等学科全国第一", "南京生活成本适中", "保研率高"],
    cons: ["就业资源不如北上广深", "部分设施老化", "仙林校区偏远", "知名度略逊于北上顶校"],
    suitable: ["目标科研/读博", "偏爱学术氛围", "理科天赋强"],
    unsuitable: ["就业优先考虑", "不喜欢学术氛围", "目标一线城市大厂"],
    dormDesc: "仙林新校区条件较好，鼓楼老校区部分宿舍设施老旧。4-6人间。",
    canteenDesc: "食堂品种一般，口味中规中矩，价格较实惠。"
